version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ramo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ramo_db
    ports:
      - "5432:5432"
    volumes:
      - ramo_pgdata:/var/lib/postgresql/data

volumes:
  ramo_pgdata: